mainprefix = "x"
prefix = "grad_adminmessages"

name = "Gruppe Adler Admin Messages"

[properties]
author = "Salbei"
url = "https://github.com/gruppe-adler/grad_adminMessages/releases"

[files]
include = [
    "meta.cpp",
    "mod.cpp",
    "logo_active_ca.paa",
    "logo_ca.paa",
    "overview_co.paa",
    "logo_small_ca.paa",
    "LICENSE",
    "README.md"
]

exclude = [
    "*.psd",        # By default this list is empty
    "*.md",
    "/.vscode/",
]

[version]
path = "addons/main/script_version.hpp"


[lints.sqf]
command_case = false